Skripsi/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from . import views
from django.urls import path

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    path('',views.dashboard,name="dashboard"),
    path('logout/',views.user_logout,name="logoutUser"),
    path('profile/',include('profileUser.urls')),
    path('aboutUs/',views.aboutUs,name='aboutus'),
    path('register/',include('register.urls'),name="register"),
    path('product/',include('product.urls'),name="product"),
    path('brand/',include('profileBrand.urls'),name="brand"),
    path('carousel/',include('carousel.urls'),name="carousel"),
    path('reportList/',include('report.urls'),name="report"),
    path('verify/<auth_token>',views.verifyEmail,name="verify"),
    path('forgot_Pass/<auth_token>',views.forgotPasswordForm,name="forgot_pass"),
    #quick qearch
    path('search/',views.search,name="search"),

    #advance search
    path('advancesearch/',include('advancesearch.urls'),name="aSearch"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

report/urls.py
from django.urls import path
from . import views

urlpatterns = [
   path('',views.reportList,name="reportList"),
   path('<user_select>/<brand>/<productName>',views.reportListView,name="reportListView"),
   path('<user_select>/<brand>/<productName>/approve',views.approveReport,name="approveReport"),
   path('<user_select>/<brand>/<productName>/reject',views.rejectReport,name="rejectReport"),
   # path('<user_select>/<brand>/<productName>/reject',views.reportListView,name="reportListView"),
]

Skripsi/forms.py
from django import forms

class ForgotPasswordForm (forms.Form):
    userPassword = forms.CharField(
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'class':'form-control',
                'placeholder':'new password'
            }
        ),
        label='userPassword',
    )

    confUserPassword = forms.CharField(
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'class':'form-control',
                'placeholder':'confirm password'
            }
        ),
        label='confUserPassword',
    )

templates/snippets/footer.html
{% load static %}

{% if user.is_authenticated %}
  <span id="logged_in" style="display: none;" value="true">true</span>
{% else %}
  <span id="logged_in" style="display: none;" value="false">false</span>
{% endif %}

<!-- Modal Sign Up-->
<div class="modal fade" id="signUpModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" style="margin: auto; padding-left: 20%;" id="exampleModalLongTitle">Choose your Role</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <a href="{% url 'musicStore' %}" class="graybutton" style="color: white;"><i class="fa fa-music pr-2" aria-hidden="true"></i>Music Store</a>
        <a href="{% url 'regularUser' %}" class="graybutton" style="color: white;"><i class="fa fa-user pr-2" aria-hidden="true"></i>Regular User</a>
      </div>
    </div>
  </div>
</div>

<!-- Modal Login-->
<div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" style="margin: auto; padding-left: 20%;" id="exampleModalLongTitle">Log In</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="container" style="width: 80%; height: 80%;">
          <form method="POST">

            {% csrf_token %}

            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-info"> 
                      <span id="msg" value="{{ message }}">{{ message }}</span>  
                    </div>
                {% endfor %}
            {% endif %}
            
            <div class="d-flex">
              <div class="mr-auto"><h6>Email Address</h6></div>
              <small><a id="register" href="#signUpModal" data-toggle="modal" data-target="#signUpModal" style="color: #38a100;">Register</a></small>
            </div>

              {% comment %} {{form.userEmail}} {% endcomment %}
              <input type="email" name="userEmail" class="form-control" required="" id="id_userEmail" required>
              <small class="text-muted">example:email@musikita.com</small>

            <div class="pt-3">
                <div class="mr-auto"><h6>Password</h6></div>

                {% comment %} {{form.userPassword}} {% endcomment %}
                <input type="password" name="userPassword" class="form-control" required="" id="id_userPassword" required>
                <small>
                  <a id="forgotPass" href="#forgotPasswordModal" data-toggle="modal" data-target="#forgotPasswordModal" style="color: #38a100;">Forgot Your Password?</a>
                </small>
            </div>
            <div class="d-flex flex-row-reverse bd-highlight pt-3">
              <div class="p-2 bd-highlight"><button type="submit" class="greenbutton">Login</button></div>
            </div>
            <input name="isLogin" value="1" style="display: none;">
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Modal review-->
<div class="modal fade" id="reviewLoginFirstModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        {{messageModal}}
      </div>
    </div>
  </div>
</div>

<!-- Forgot Password review-->
<div class="modal fade" id="forgotPasswordModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" style="margin: auto; padding-left: 20%;" id="exampleModalLongTitle">Forgot Password</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="container" style="width: 80%; height: 80%;">
          <form method="POST">

            {% csrf_token %}
            
            <div class="d-flex">
              <div class="mr-auto"><h6>Email Address</h6></div>
            </div>

              {% comment %} {{form.userEmail}} {% endcomment %}
              <input type="email" name="userEmail" class="form-control" required="" id="id_userEmail" required>
              <small class="text-muted">example:email@musikita.com</small>

            <div class="d-flex flex-row-reverse bd-highlight pt-3">
              <div class="p-2 bd-highlight"><button type="submit" class="greenbutton">Submit</button></div>
            </div>
            <input name="isForgotPassword" value="1" style="display: none;">
          </form>
        </div>
      </div>
    </div>
  </div>
</div>


<!-- response review-->
<div class="modal fade" id="responseModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        {% if messages %}
            {% for message in messages %}
              <span id="responseMsg" value="{{ message }}">{{ message }}</span>  
            {% endfor %}
        {% endif %}
      </div>
    </div>
  </div>
</div>

<footer class="bg-secondary da-section">
    <div class="container text-white">
      <div class="row">
        <div class="col-md-5">
          <div class="h2 mb-4">MusiKita.com</div>
          <p class="mb-3">info@MusiKita.com</p>
          <p>+1 502-257-1157</p>
        </div>
        <div class="col-md-3">
          <div class="h6 pb-4">Copyright</div>
          <p class="pb-1">&copy; Musikita.com. All rights reserved.</p>
          <p>Design - <a class="credit" href="https://templateflip.com" target="_blank">TemplateFlip</a></p>
        </div>
      </div>
    </div>
  </footer>

templates/snippets/footerAndScripts.html
{% load static %}

{% if user.is_authenticated %}
  <span id="logged_in" style="display: none;" value="true">true</span>
{% else %}
  <span id="logged_in" style="display: none;" value="false">false</span>
{% endif %}

<!-- Modal Sign Up-->
<div class="modal fade" id="signUpModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" style="margin: auto; padding-left: 20%;" id="exampleModalLongTitle">Choose your Role</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <a href="{% url 'musicStore' %}" class="graybutton" style="color: white;"><i class="fa fa-music pr-2" aria-hidden="true"></i>Music Store</a>
        <a href="{% url 'regularUser' %}" class="graybutton" style="color: white;"><i class="fa fa-user pr-2" aria-hidden="true"></i>Regular User</a>
      </div>
    </div>
  </div>
</div>

<!-- Modal Login-->
<div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" style="margin: auto; padding-left: 20%;" id="exampleModalLongTitle">Log In</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="container" style="width: 80%; height: 80%;">
          <form method="POST">

            {% csrf_token %}

            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-info"> 
                      <span id="msg" value="{{ message }}">{{ message }}</span>  
                    </div>
                {% endfor %}
            {% endif %}
            
            <div class="d-flex">
              <div class="mr-auto"><h6>Email Address</h6></div>
              <small><a id="register" href="#signUpModal" data-toggle="modal" data-target="#signUpModal" style="color: #38a100;">Register</a></small>
            </div>

              {% comment %} {{form.userEmail}} {% endcomment %}
              <input type="email" name="userEmail" class="form-control" required="" id="id_userEmail" required>
              <small class="text-muted">example:email@musikita.com</small>

            <div class="pt-3">
                <div class="mr-auto"><h6>Password</h6></div>

                <div class="input-group" id="show_hide_password">
                  <input type="password" name="userPassword" class="form-control" required="" id="id_userPassword" required>
                  <div class="input-group-addon pt-1 pl-1">
                    <a href="" style="color:black;"><i class="fa fa-eye-slash" aria-hidden="true"></i></a>
                  </div>
                </div>
                
                
                <small>
                  <a id="forgotPass" href="#forgotPasswordModal" data-toggle="modal" data-target="#forgotPasswordModal" style="color: #38a100;">Forgot Your Password?</a>
                </small>



            </div>
            <div class="d-flex flex-row-reverse bd-highlight pt-3">
              <div class="p-2 bd-highlight"><button type="submit" class="greenbutton">Login</button></div>
            </div>
            <input name="isLogin" value="1" style="display: none;">
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Modal review-->
<div class="modal fade" id="reviewLoginFirstModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        {{messageModal}}
      </div>
    </div>
  </div>
</div>

<!-- Forgot Password review-->
<div class="modal fade" id="forgotPasswordModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" style="margin: auto; padding-left: 20%;" id="exampleModalLongTitle">Forgot Password</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="container" style="width: 80%; height: 80%;">
          <form method="POST">

            {% csrf_token %}
            
            <div class="d-flex">
              <div class="mr-auto"><h6>Email Address</h6></div>
            </div>

              {% comment %} {{form.userEmail}} {% endcomment %}
              <input type="email" name="userEmail" class="form-control" required="" id="id_userEmail" required>
              <small class="text-muted">example:email@musikita.com</small>

            <div class="d-flex flex-row-reverse bd-highlight pt-3">
              <div class="p-2 bd-highlight"><button type="submit" class="greenbutton">Submit</button></div>
            </div>
            <input name="isForgotPassword" value="1" style="display: none;">
          </form>
        </div>
      </div>
    </div>
  </div>
</div>


<!-- response review-->
<div class="modal fade" id="responseModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        {% if messages %}
            {% for message in messages %}
              <span id="responseMsg" value="{{ message }}">{{ message }}</span>  
            {% endfor %}
        {% endif %}
      </div>
    </div>
  </div>
</div>

<footer class="bg-secondary da-section">
    <div class="container text-white">
      <div class="row">
        <div class="col-md-4">
          <div class="h2 mb-4">MusiKita.com</div>
          <p class="mb-3">musikita726@gmail.com</p>
        </div>

         <div class="col-md-3">
          <div class="h6 pb-2">Explore</div>
          <ul>
            <li><a style="color: white;" href="{% url 'dashboard' %}">Home</a></li>
            <li><a style="color: white;" href="{% url 'aboutus' %}">About Musikita</a></li>
            <li><a style="color: white;" href="{% url 'advanceSearch' %}">Browse Product</a></li>
          </ul>
        </div> 

        <div class="col-md-2">
          <div class="h6 pb-2">Follow Us</div>
          <ul>
            <li class="mb-1"><a class="da-social-link" ><i class="fab fa-twitter" aria-hidden="true"></i><span class="ml-2">@musikita</span></a></li>
            <li class="mb-1"><a class="da-social-link" ><i class="fab fa-facebook-f" aria-hidden="true"></i><span class="ml-2">Musikita.com</span></a></li>
            <li class="mb-1"><a class="da-social-link" ><i class="fab fa-instagram" aria-hidden="true"></i><span class="ml-2">@usikita</span></a></li>
            <li class="mb-1"><a class="da-social-link" ><i class="fab fa-youtube" aria-hidden="true"></i><span class="ml-2">MusikitaCom</span></a></li>
          </ul>
        </div>
        
        <div class="col-md-3">
          <div class="h6 pb-4">Copyright</div>
          <p class="pb-1">&copy; Musikita.com. All rights reserved.</p>
          <p>Design - <a class="credit" href="https://templateflip.com" target="_blank">TemplateFlip</a></p>
        </div>
      </div>
    </div>
</footer>

<script src="{% static 'vendor2/scripts/jquery.min.js'%}"></script>
<script src="{% static 'vendor2/scripts/bootstrap.bundle.min.js'%}"></script>
<script src="{% static 'vendor2/scripts/aos.js'%}"></script>
<script src="{% static 'vendor2/scripts/ekko-lightbox.min.js'%}"></script>
<script src="{% static 'vendor2/scripts/main.js'%}"></script>
<script src="{% static 'vendor2/scripts/seeMoreScripts.js'%}"></script>
<script src="{% static 'vendor2/scripts/custom.js'%}"></script>
<script src="{% static 'vendor2/scripts/rating.js'%}"></script>
<script src="{% static 'vendor2/scripts/tooglePassword.js'%}"></script>
<script src="{% static 'vendor2/scripts/quickSearch2.js'%}"></script>

templates/snippets/headImport.html
{% load static %}

<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="crossorigin"/>
<link rel="preload" as="style" href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;700&amp;display=swap"/>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;700&amp;display=swap" media="print" onload="this.media='all'"/>
<noscript>
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;700&amp;display=swap"/>
</noscript>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"> 

<!-- <meta name="viewport"
content="width=device-width, initial-scale=1">  -->

{% comment %} <link href="{% static 'vendor2/css/star.css' %}" rel="stylesheet"> {% endcomment %}
<link href="{% static 'vendor2/css/customs.css' %}" rel="stylesheet">
<link href="{% static 'vendor2/css/navbarCust2.css' %}" rel="stylesheet">
<link href="{% static 'vendor2/css/bootstrap2.min.css' %}" rel="stylesheet">
<link href="{% static 'vendor2/css/font-awesome/css/all.min.css' %}" rel="stylesheet">
<link href="{% static 'vendor2/css/aos.css' %}" rel="stylesheet">
<link href="{% static 'vendor2/css/ekko-lightbox.css' %}" rel="stylesheet">
<link href="{% static 'vendor2/css/main.css' %}" rel="stylesheet">
<link href="{% static 'vendor2/css/quickSearch3.css' %}" rel="stylesheet">


<noscript>
  <style type="text/css">
    [data-aos] {
        opacity: 1 !important;
        transform: translate(0) scale(1) !important;
    }
  </style>
</noscript>

templates/snippets/scripts.html
{% load static %}

<script src="{% static 'vendor2/scripts/jquery.min.js'%}"></script>
<script src="{% static 'vendor2/scripts/bootstrap.bundle.min.js'%}"></script>
<script src="{% static 'vendor2/scripts/aos.js'%}"></script>
<script src="{% static 'vendor2/scripts/ekko-lightbox.min.js'%}"></script>
<script src="{% static 'vendor2/scripts/main.js'%}"></script>
<script src="{% static 'vendor2/scripts/seeMoreScripts.js'%}"></script>
<script src="{% static 'vendor2/scripts/custom.js'%}"></script>
<script src="{% static 'vendor2/scripts/rating.js'%}"></script>
<script src="{% static 'vendor2/scripts/tooglePassword.js'%}"></script>