Skripsi/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from . import views
from django.urls import path

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    path('',views.dashboard,name="dashboard"),
    path('logout/',views.user_logout,name="logoutUser"),
    path('profile/',include('profileUser.urls')),
    path('aboutUs/',views.aboutUs,name='aboutus'),
    path('register/',include('register.urls'),name="register"),
    path('product/',include('product.urls'),name="product"),
    path('brand/',include('profileBrand.urls'),name="brand"),
    path('carousel/',include('carousel.urls'),name="carousel"),
    path('reportList/',include('report.urls'),name="report"),
    path('verify/<auth_token>',views.verifyEmail,name="verify"),
    path('forgot_Pass/<auth_token>',views.forgotPasswordForm,name="forgot_pass"),
    #quick qearch
    path('search/',views.search,name="search"),

    #advance search
    path('advancesearch/',include('advancesearch.urls'),name="aSearch"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

report/urls.py
from django.urls import path
from . import views

urlpatterns = [
   path('',views.reportList,name="reportList"),
   path('<user_select>/<brand>/<productName>',views.reportListView,name="reportListView"),
   path('<user_select>/<brand>/<productName>/approve',views.approveReport,name="approveReport"),
   path('<user_select>/<brand>/<productName>/reject',views.rejectReport,name="rejectReport"),
   # path('<user_select>/<brand>/<productName>/reject',views.reportListView,name="reportListView"),
]

review/forms.py
from django import forms

RADIO_REPORT = [
    ('Offensive Content', 'Offensive Content'),
    ('Content is Copyright', 'Content is Copyright'),
    ('SPAM or Advertising', 'SPAM or Advertising'),
    ('Mature Content', 'Mature Content'),
    ('Distruptive Posting', 'Distruptive Posting'),
    ('Insults of Other User', 'Insults of Other User'),
    ('Illegal Activities', 'Illegal Activities'),
    ('Other Strong Reason', 'Other Strong Reason'),
]

class ReviewForm (forms.Form):
    reviewTitle = forms.CharField(
        required=True,
        label='reviewTitle',
        widget=forms.TextInput(
            attrs={
                'class':'form-control',
                'placeholder':'Title For Review (max. 60 character)'
            }
        )
    )

    reviewDescription = forms.CharField(
        required=True,
        label='reviewDescription',
        widget=forms.Textarea(
            attrs={
                'class':'form-control',
                'placeholder':'Review Description (min. 75 character)'
            }
        )
    )

    sellStatus = forms.BooleanField(required=False)

    soldQty = forms.IntegerField(
        required=True,
        label='soldQty',
        widget=forms.NumberInput(
            attrs={
                'class':'form-control',
                'placeholder':'0'
            }
        )
    )

class ReportForm (forms.Form):
    reportReason = forms.ChoiceField(
        choices=RADIO_REPORT,
        widget=forms.RadioSelect(),
        required=True
    )    

report/views.py
from register.forms import RejectionReason
from review.views import updateReviewAvg
from register.models import User
from django.contrib.sites.shortcuts import get_current_site
from product.models import Product
from Skripsi.decorator import allowed_users
from django.contrib.auth.decorators import login_required
from Skripsi.views import countReport, countUserPending, sendMail
from django.db.models.query import QuerySet
from django.shortcuts import redirect, render
from review.models import Report, Review
from django.db import connection
from django.core.paginator import Paginator

@login_required
@allowed_users(allowed_roles=['Admin'])
def reportList (request):
    reportUserList = []
    with connection.cursor() as cursor:
        raw_sql =""" 
                    select u.userName, rev.title, p.productName, b.brandName, rev.dtm_crt, rev.rating from review_report as rep
                    join review_review as rev on rev.reviewId = rep.reviewId_id
                    join product_product as p on rev.productId_id = p.productId
                    join product_brand as b on p.brandId_id = b.brandId
                    join register_user as u on rev.userID_id = u.userID
                    group by rep.reviewId_id
                """            
        cursor.execute(raw_sql)

        for qux in cursor.fetchall():
            reportUserList.append({
                'userName': qux[0],
                'reviewTitle': qux[1],
                'productName': qux[2],
                'productBrand': qux[3],
                'dtm_crt': qux[4],
                'ratingReview': qux[5]
            })
    
    getReportListByPage = None
    if reportUserList:
        paginator = Paginator(reportUserList,4)
        page_number = request.GET.get('page', 1)
        getReportListByPage = paginator.get_page(page_number)

        if getReportListByPage.has_next():
            next_url = f'?page={getReportListByPage.next_page_number()}'
        else:
            next_url = ''

            if getReportListByPage.has_previous():
                prev_url = f'?page={getReportListByPage.previous_page_number()}'
            else:
                prev_url = ''
    else:
        getReportListByPage = None
        next_url = ''
        prev_url = ''

    context = {
        'obj':getReportListByPage,
        'userPending': countUserPending(request),
        'reportUser': countReport(request),
        'next_page_url': next_url,
        'prev_page_url': prev_url
    }

    return render(request,'reportList.html', context)

@login_required
@allowed_users(allowed_roles=['Admin'])
def reportListView (request, user_select, brand, productName):
    try:
        getProduct = Product.objects.select_related(
                            'brandId').get(
                            productName = productName,
                            brandId__brandName = brand)

        obj = Review.objects.select_related('userID').get(
                    productId = getProduct.productId,
                    userID__userName = user_select
                )

        getReportReason = Report.objects.select_related('reviewId').filter(
                            reviewId__reviewId = obj.reviewId
                          ).values('reason').distinct()

        getReportData = Report.objects.select_related('reviewId','userID').filter(
                            reviewId__reviewId = obj.reviewId)
        
        context = { 
            'obj': obj,
            'brand': brand,
            'productName': productName,
            'reportReasonList': getReportReason,
            'reportData':getReportData,
            'reportUser': countReport(request),
            'userPending': countUserPending(request)
        }   

        return render(request,'reportListView.html', context)

    except Exception as e:
        print(e)
        context = { 
            'message': 'error'
        }   
        return render(request,'error.html', context)

def approveReport (request, user_select, brand, productName):
    try:
        getProduct = Product.objects.select_related(
                            'brandId').get(
                            productName = productName,
                            brandId__brandName = brand)

        obj = Review.objects.select_related('userID').get(
                    productId = getProduct.productId,
                    userID__userName = user_select
                )
        
        getReportReason = Report.objects.select_related('reviewId').filter(
                            reviewId__reviewId = obj.reviewId
                          ).values('reason').distinct()

        getReasonArray = []

        i = 0
        while i < len(getReportReason):
            getReasonArray.append(getReportReason[i]['reason'])
            i += 1
        
        reason = ""
        for item in getReasonArray:
            reason += '- ' + item +'\n'
        
        domain = get_current_site(request).domain
        message =""" 
                    hi """+user_select+""",
                    we like to inform you about your review with a title \" """+obj.title+""" \"
                    in """+getProduct.productName+""", has been reported due to: \n
                    """+reason+"""
                    \n
                    thank you
                    http://"""+domain+"""
                """    
        getUser = User.objects.get(userName = user_select)
        sendMail (domain, getUser, 'approve_report',message)

        obj.delete()
        updateReviewAvg(getProduct)

        return redirect('reportList')
    except Exception as e:
        print(e)
        context = { 
            'message': 'error'
        }   
        return render(request,'error.html', context)

def rejectReport (request, user_select, brand, productName):
    try:
        if request.method != 'POST':
            rejectionForm = RejectionReason()
            context = {
                'form': rejectionForm,
                'userPending': countUserPending(request)
            }
            return render(request,'rejectionReason.html', context)
        else :
            rejectionReason = request.POST.get('reason')

            getProduct = Product.objects.select_related(
                            'brandId').get(
                            productName = productName,
                            brandId__brandName = brand)

            obj = Review.objects.select_related('userID').get(
                        productId = getProduct.productId,
                        userID__userName = user_select
                    )
        
            getReportReviewData = Report.objects.select_related('reviewId','userID').filter(
                                reviewId__reviewId = obj.reviewId
                            )

            getUserEmailList = []

            for email in getReportReviewData:
                getUserEmailList.append(email.userID.email)


            domain = get_current_site(request).domain
            message =""" 
                        Hello Users!!,
                        Unfortunately your review report about \" """+obj.title+""" \" from """+user_select+"""
                        in """+getProduct.productName+""", has been rejected by admin because:\n\n
                        """+rejectionReason+"""
                        \n\n
                        thank you
                        http://"""+domain+"""
                    """    
            getUser = User.objects.get(userName = user_select)
            sendMail (domain, getUserEmailList, 'reject_report',message)

            getReportReviewData.delete()
            
            return redirect('reportList')

    except Exception as e:
        print(e)
        context = { 
            'message': 'error'
        }   
        return render(request,'error.html', context)

    return 'success'
        

templates/addInviteRegisterBrand.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{context}}</title>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.8.7/chosen.min.css" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.8.7/chosen.jquery.js"></script>
    {% include "snippets/headImport.html" %}

</head>
<body>

    <div class="container">

        <h1 class="pb-5 pt-5">{{context}}</h1>

        <form method='POST'>
        
            {% csrf_token %}

            {% if messages %}
            
                {% for message in messages %}
                    <div class="alert alert-info"> 
                        {{ message }}
                    </div>
                {% endfor %}
            
            {% endif %}


            {% if context == 'Add Brand' %}
                <div class="pt-3">
                    {{ form.brandName }}
                </div>
            {% elif context == 'Invite Brand' %}
                <h5>Brand Name</h5>
                <div class="pt-3">
                    {{ form.brandName }}
                </div>
                <div class="pt-3">
                    {{ form.email }}
                </div>
                <div class="pt-3">
                    {{ form.message }}
                </div>
            {% else %}
                <div class="pt-3">
                    {{ form.email }}
                </div>
                <div class="pt-3">
                    <div class="input-group" id="show_hide_password">
                    {{ form.password }}
                    <div class="input-group-addon pt-1 pl-1">
                        <a href="" style="color:black;"><i class="fa fa-eye-slash" aria-hidden="true"></i></a>
                    </div>
                    </div>
                </div>
                
                <div class="pt-3">
                    <div class="input-group" id="show_hide_password_confirm">
                    {{ form.confirm_pass }}
                    <div class="input-group-addon pt-1 pl-1">
                        <a href="" style="color:black;"><i class="fa fa-eye-slash" aria-hidden="true"></i></a>
                    </div>
                    </div>
                </div>
                <div class="pt-3">
                    {{ form.brandWebsiteUrl }}
                </div>
                <div class="pt-3">
                    {{ form.description }}
                </div>
            {% endif %}
            
            <div class="d-flex flex-row-reverse bd-highlight pb-5">

                <div class="p-2 bd-highlight">
                    <button type="submit" class="greenbutton">Submit</button>
                </div>
                {% if user.is_authenticated and request.user.groups.all.0.name == 'Admin' %}
                    <div class="p-2 bd-highlight">
                        <a type="submit" class="greenbutton" href="{% url 'brandcontrol' %}"style="text-decoration: none;">Back</a>
                    </div>                        
                {% endif %}
            </div>
        </form>
    </div>

    <script src="{% static 'vendor2/scripts/dropdown.js'%}"></script>
    <script>
        $(".chosen").chosen();
    </script>
    {% include "snippets/scripts.html" %}
    
</body>



</html>

templates/addProductEdit.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Edit Product - {{ product.productName }}</title>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.8.7/chosen.min.css" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.8.7/chosen.jquery.js"></script>
    {% include "snippets/headImport.html" %}

</head>
<body>

    {% include "snippets/navbar.html" %}

    <div class="container">
        <h1 class="pb-5 pt-5">Edit Product: {{ product.productName }}</h1>
        <form method='POST' enctype="multipart/form-data">
        
            {% csrf_token %}

            {% if messages %}
            
                {% for message in messages %}
                    <div class="alert alert-info"> 
                        {{ message }}
                    </div>
                {% endfor %}
            
            {% endif %}

            <h5 class="pt-3">Product Name</h5>

            <div class="pt-3">
               <textarea name="productName" class="form-control" id="exampleFormControlTextarea1" rows="1">{{ product.productName }}</textarea>
            </div>

            <h5 class="pt-3">Product Brand</h5>

            {% if request.user.groups.all.0.name == 'Brand' %}
                <input type="text" class="form-control" name="productBrand" value="{{ request.user.username }}" readonly><br>
            {% else %}
                <div class="pt-3">
                    {{ form.productBrand }}
                </div>
            {% endif %}

            <span id="productName" style="display: none;" value="{{ product.productName }}">{{ product.productName }}</span>
            <span id="brand" style="display: none;" value="{{product.brandId.brandName}}">{{product.brandId.brandName}}</span>


            <h5 class="pt-3">Product Category</h5>
            
            <div class="pt-3" id="category">
                <select class="form-control" id="categoryddl" name="category" required>
                    <option disabled value="" selected="">---------</option>
                </select>
            </div>

            <h5 class="pt-3">Product Sub-Category</h5>

            <div class="pt-3" id="subcategory">
                <select class="form-control" id="subcategoryddl" name="subCategory" required>
                    <option disabled value="" selected="" id="subCategoryText">---------</option>
                </select>
            </div>

            <h5 class="pt-3">Description</h5>

            <div class="pt-3">
                <textarea name="description" class="form-control" id="exampleFormControlTextarea1" rows="3">{{product.description}}</textarea>
            </div>

            <h5 class="pt-3">Youtube Video Url</h5>

            <div class="pt-3">
                <textarea name="videoUrl" class="form-control" id="exampleFormControlTextarea1" rows="1">{{ product.videoUrl }}</textarea>
            </div>
            
            
            <div class="d-flex flex-row-reverse bd-highlight pb-5">
                <div class="p-2 bd-highlight">
                    <button type="submit" class="greenbutton">Save</button>
                </div>
                <div class="p-2 bd-highlight">
                    {% if context == 'editProductRating' %}
                        <a type="submit" class="greenbutton" href="{% url 'showProduct' brand=product.brandId.brandName productName=product.productName %}"style="text-decoration: none;">Back</a>
                    {% elif context == 'editProductBrand' %}
                        <a type="submit" class="greenbutton" href="{% url 'brandPage' brandName=product.brandId.brandName sort='By Date' %}"style="text-decoration: none;">Back</a>
                    {% endif %}
                </div>
            </div>
        </form>
    </div>

    <script src="{% static 'vendor2/scripts/dropdownEdit.js'%}"></script>
    <script>
        $(".chosen").chosen();
    </script>
    {% include "snippets/footer.html" %}
    <script src="{% static 'vendor2/scripts/jquery.min.js'%}"></script>
    <script src="{% static 'vendor2/scripts/bootstrap.bundle.min.js'%}"></script>
    <script src="{% static 'vendor2/scripts/aos.js'%}"></script>
    <script src="{% static 'vendor2/scripts/ekko-lightbox.min.js'%}"></script>
    <script src="{% static 'vendor2/scripts/main.js'%}"></script>
    <script src="{% static 'vendor2/scripts/seeMoreScript.js'%}"></script>
    <script src="{% static 'vendor2/scripts/rating.js'%}"></script>
    
</body>



</html>

templates/error.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Register</title>
    {% include "snippets/headImport.html" %}
</head>
<body>

    <div class="container">

        <h1 class="pb-3 pt-5">{{message}}</h1>
        <h6>Go Back To <a href="/">Homepage</a></h6>

    </div>

    {% include "snippets/scripts.html" %}
    
</body>



</html>

templates/forgotPassword.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Register</title>
    {% include "snippets/headImport.html" %}
</head>
<body>

    <div class="container">

        <h1 class="pb-5 pt-5">Reset Password > {{username}}</h1>

        <form method='POST'>
        
            {% csrf_token %}

            {% if messages %}
            
                {% for message in messages %}
                    <div class="alert alert-info"> 
                        {{ message }}
                    </div>
                {% endfor %}
            
            {% endif %}

            <div class="pt-3">
                <div class="input-group" id="show_hide_password">
                  {{ form.userPassword }}
                  <div class="input-group-addon pt-1 pl-1">
                    <a href="" style="color:black;"><i class="fa fa-eye-slash" aria-hidden="true"></i></a>
                  </div>
                </div>
            </div>
            <div class="pt-3">
                <div class="input-group" id="show_hide_password">
                  {{ form.confUserPassword }}
                  <div class="input-group-addon pt-1 pl-1">
                    <a href="" style="color:black;"><i class="fa fa-eye-slash" aria-hidden="true"></i></a>
                  </div>
                </div>
            </div>
            
            <div class="d-flex flex-row-reverse bd-highlight pb-5">
                <div class="p-2 bd-highlight">
                    <button type="submit" class="greenbutton">submit</button>
                </div>
            </div>
        </form>
    </div>

    {% include "snippets/scripts.html" %}
    
</body>



</html>

templates/manageCarousel.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Carousel Management</title>
    {% include "snippets/headImport.html" %}
</head>
<body>
    {% include "snippets/navbar.html" %}
    <div class="container">

        <h1 class="pb-5 pt-5">Carousel List</h1>
        <div class="d-flex flex-row bd-highlight pt-3">
          <div class="p-2 bd-highlight"><a type="submit" style="text-decoration: none;" class="greenbutton" href="{% url 'addcarousel' %}">Add Carousel</a></div>
        </div>
        
        <form method='POST'>
          {% csrf_token %}
          
          <div class="row">
            
            {% for obj in data %}
                <div class="col-sm-6 pb-3">
                    <div class="card">
                        <div class="card-body">
                          <img src="{{obj.0.carouselIMG.url}}" width="100%" alt="image">
                          {{ obj.1.imageActive }}
                          <a href="{% url 'deleteCarousel' carouselObject=obj.0.carouselId %}" style="color: rgb(187, 42, 42); text-decoration: none;">
                            <i class="fas fa-window-close"></i>
                          </a>
                        </div>
                    </div>
                </div>
            {% endfor %}
          </div>
          <div class="d-flex flex-row-reverse bd-highlight pb-5">
            <div class="p-2 bd-highlight">
                <button type="submit" class="greenbutton">Save</button>
            </div>
          </div>
        </form>
    </div>

    {% include "snippets/footerAndScripts.html" %}
    
</body>



</html>

templates/scoreRatingEdit.html
{% load static %}

<!DOCTYPE html>
<html lang="en-US">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Review Score Edit - {{productName}}</title>
  
  {% include "snippets/headImport.html" %}
  
</head>
<body id="top">
      
{% include "snippets/navbar.html" %}

    <div class="container">
        <div class="separator"><div class="h1 text-center" ><span>{{brand}}: </span><span>{{productName}}</span></div></div>

        <form method='POST'>
            {% csrf_token %}

            {% if messages %}
            
                {% for message in messages %}
                    <div class="alert alert-info"> 
                        {{ message }}
                    </div>
                {% endfor %}
            
            {% endif %}
            
            <div class="mt-3">
                <h5>Rating Score</h5>
                <div class="d-flex flex-row">
                    <div class="p-1">
                        <div class="star-widget">
                            <input type="radio" name="rate" id="rate-10" onclick="score();" value="10">
                            <label onmouseover="addNum(10)" onmouseout="removeNum()" for="rate-10" class="fas fa-square-full"></label>
                            <input type="radio" name="rate" id="rate-9" onclick="score();" value="9">
                            <label onmouseover="addNum(9)" onmouseout="removeNum()" for="rate-9" class="fas fa-square-full"></label>
                            <input type="radio" name="rate" id="rate-8" onclick="score();" value="8">
                            <label onmouseover="addNum(8)" onmouseout="removeNum()" for="rate-8" class="fas fa-square-full"></label>
                            <input type="radio" name="rate" id="rate-7" onclick="score();" value="7">
                            <label onmouseover="addNum(7)" onmouseout="removeNum()" for="rate-7" class="fas fa-square-full"></label>
                            <input type="radio" name="rate" id="rate-6" onclick="score();" value="6">
                            <label onmouseover="addNum(6)" onmouseout="removeNum()" for="rate-6" class="fas fa-square-full"></label>
                            <input type="radio" name="rate" id="rate-5" onclick="score();" value="5">
                            <label onmouseover="addNum(5)" onmouseout="removeNum()" for="rate-5" class="fas fa-square-full"></label>
                            <input type="radio" name="rate" id="rate-4" onclick="score();" value="4">
                            <label onmouseover="addNum(4)" onmouseout="removeNum()" for="rate-4" class="fas fa-square-full"></label>
                            <input type="radio" name="rate" id="rate-3" onclick="score();" value="3">
                            <label onmouseover="addNum(3)" onmouseout="removeNum()" for="rate-3" class="fas fa-square-full"></label>
                            <input type="radio" name="rate" id="rate-2" onclick="score();" value="2">
                            <label onmouseover="addNum(2)" onmouseout="removeNum()" for="rate-2" class="fas fa-square-full"></label>
                            <input type="radio" name="rate" id="rate-1" onclick="score();" value="1">
                            <label onmouseover="addNum(1)" onmouseout="removeNum()" for="rate-1" class="fas fa-square-full"></label>
                        </div>
                    </div>
                    <div class="p1 pl-3">
                        <h4 id="score">0</h4>
                    </div>
                </div>
            </div>


            <div class="pt-3">
                <h5>Review Title</h5>
                <textarea name="reviewTitle" class="form-control" id="exampleFormControlTextarea1" rows="1" required>{{review.title}}</textarea>
            </div>

            <div class="pt-3">
                <h5>Description</h5>
                <textarea name="reviewDescription" class="form-control" id="exampleFormControlTextarea1" rows="4" required>{{review.description}}</textarea>
            </div>
            

            {% if request.user.groups.all.0.name == 'Mus_Store' %}
                <div class="pt-5 mt-5 pb-5 mb-5">
                    <div class="form-check">
                        {% if review.sellStatus == True %}
                            <input type="checkbox" name="sellStatus" id="id_sellStatus" checked>
                        {% else %}
                            <input type="checkbox" name="sellStatus" id="id_sellStatus">
                        {% endif %}
                        <label class="form-check-label" for="flexCheckDefault">
                            <h5>Are you selling this product in your Music Store?</h5>
                        </label>
                    </div>
                </div>
            {% endif %}


            <div class="d-flex flex-row-reverse bd-highlight pb-5">
                <div class="p-2 bd-highlight"><button type="Submit" class="greenbutton">Submit Review</button></div>
                {% if backButton == 'profilePage' %}
                    <div class="p-2 bd-highlight"><a class="greenbutton" href="{% url 'profilePage' userName=User.userName %}"style="text-decoration: none;">back</a></div>
                {% else %}
                    <div class="p-2 bd-highlight"><a href="{% url 'showProduct' brand=brand productName=productName %}" class="greenbutton" id="confirm-btn">back</a></div>
                {% endif %}
            </div>
        </form>
    </div>



{% include "snippets/footer.html" %}
<script src="{% static 'vendor2/scripts/jquery.min.js'%}"></script>
<script src="{% static 'vendor2/scripts/bootstrap.bundle.min.js'%}"></script>
<script src="{% static 'vendor2/scripts/aos.js'%}"></script>
<script src="{% static 'vendor2/scripts/ekko-lightbox.min.js'%}"></script>
<script src="{% static 'vendor2/scripts/main.js'%}"></script>
<script src="{% static 'vendor2/scripts/seeMoreScript.js'%}"></script>
<script src="{% static 'vendor2/scripts/rating.js'%}"></script>

</body>
</html>

templates/token-send.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Register</title>
    {% include "snippets/headImport.html" %}
</head>
<body>

    <div class="container">

        <h1 class="pb-3 pt-5">We Have Send You an Email for Verification</h1>
        <h6>Go Back To <a href="/">Homepage</a></h6>

    </div>

    {% include "snippets/scripts.html" %}
    
</body>



</html>

templates/verifiedMusicStore.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Register</title>
    {% include "snippets/headImport.html" %}
</head>
<body>

    <div class="container">

        <h1 class="pb-3 pt-5">Your Account Has Been Verified, But You Need to wait for Admin Approval to use this account!!</h1>
        <h5>Admin will send you email immediately</h5>
        <h6>Go Back To <a href="/">Homepage</a></h6>

    </div>

    {% include "snippets/scripts.html" %}
    
</body>



</html>